---
- hosts: localhost
  vars:
    install_pkgs: [ 'vim','tmux']
  tasks:
    - name: Run on CentOS
      yum:
        name: "{{ item }}"
        state: latest
      with_times: "{{ install_pkgs }}"
      when: ansible_distribution == "CentOS"

    - name: Run on Ubuntu
      apt:
        name: "{{ item }}"
        state: latest
      with_times: "{{ install_pkgs }}"
      when: ansible_distribution == "Ubuntu"

    - name: Run on openSUSE
      zypper:
        name: "{{ item }}"
        state: latest
      with_times: "{{ install_pkgs }}"
      when: ansible_distribution == "openSUSE Leap"
      
    - name: Copy config
      copy:
        src: ../vimrc
        dest: ~/.vimrc
        mode: 0644

    - name: Copy config
      copy:
        src: ../tmux.conf
        dest: ~/.tmux.conf
        mode: 0644
    
    
